version: '3.9'

services:
  counting:
    container_name: counting
    user: root
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/counting
      - ./creds.json:/secrets/creds.json
    env_file:
      - ./.env
    restart: always
